module CP
    TILE_SIZE = 48
    MAX_ROWS = 12
    MAX_COLS = 16
    SCREEN_WIDTH = TILE_SIZE * MAX_COLS
    SCREEN_HEIGHT = TILE_SIZE * MAX_ROWS
    
    #World Setting
    MAX_WORLD_ROWS = 40
    MAX_WORLD_COLS = 40
    WOLRD_WIDTH = MAX_WORLD_COLS * TILE_SIZE
    WOLRD_HEIGHT = MAX_WORLD_ROWS * TILE_SIZE
end


